apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ninja-api
spec:
  defaultBackend:
    service:
      name: auth-http
      port:
        number: 3003
  rules:
    - http:
        paths:
          - path: /reservations/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: reservations
                port:
                  number: 3004
          - path: /auth/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-http
                port:
                  number: 3003